version: '2.1'

services:

  apiserver_image:
    build:
      context: .
      dockerfile: Dockerfile
    image: apiserver:local
    container_name: api_local

  apiserver:
    image: apiserver:local
    container_name: airflow_apiserver
    restart: always
    ports:
      - "5000:5000"
    entrypoint: "python"
    command: "app.py"
